### ISSUE TITLE
Does changes in StyleGAN2 model nessary?

### ISSUE THREAD

**Issue by shartoo** [850552586/Latent-To-Latent#10]
Compared with codes of python implement of [StyleGAN2](https://github.com/rosinality/stylegan2-pytorch),there are many changes in your repo,such as 
![image](https://github.com/850552586/Latent-To-Latent/assets/5716282/aec8ca05-d29b-47f4-b947-38027f8325fb)

![image](https://github.com/850552586/Latent-To-Latent/assets/5716282/e7a8f237-eeb6-455c-9fb2-d46896f20a3a)

I don't know if this is nessary. But current training code cannot run successful, sth wrong with cuda device

```
Loading ReStyle e4e from checkpoint: ../pretrained/restyle_e4e_ffhq_encode.pt
Training - 1 begining!
  0%|          | 0/563 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\workspace\python\Latent-To-Latent-main\training\trainer.py", line 159, in <module>
    train(args)
  File "E:\workspace\python\Latent-To-Latent-main\training\trainer.py", line 54, in train
    loss_cur = train_imgs_batch(img,training_models,latent_model,mtcnn,resnet,configs,save_path,train=True,i=i,device=device)
  File "E:\workspace\python\Latent-To-Latent-main\training\trainer.py", line 82, in train_imgs_batch
    _,w_latents = get_latent(imgs,t_model.encoder,configs)
  File "E:\workspace\python\Latent-To-Latent-main\utils\latent_utils.py", line 12, in get_latent
    avg_image = get_average_image(net)
  File "E:\workspace\python\Latent-To-Latent-main\utils\latent_utils.py", line 31, in get_average_image
    avg_image = net(net.latent_avg.unsqueeze(0),
  File "D:\soft\python39\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\workspace\python\Latent-To-Latent-main\models\e4e.py", line 80, in forward
    images, result_latent = self.decoder([codes],
  File "D:\soft\python39\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\workspace\python\Latent-To-Latent-main\models\stylegan2\model.py", line 521, in forward
    out = self.conv1(out, latent[:, 0], noise=noise[0])
  File "D:\soft\python39\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\workspace\python\Latent-To-Latent-main\models\stylegan2\model.py", line 332, in forward
    out = self.conv(input, style)
  File "D:\soft\python39\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\workspace\python\Latent-To-Latent-main\models\stylegan2\model.py", line 235, in forward
    style = self.modulation(style).view(batch, 1, in_channel, 1, 1)
  File "D:\soft\python39\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\workspace\python\Latent-To-Latent-main\models\stylegan2\model.py", line 153, in forward
    out = F.linear(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)
```

manual change them into cuda will leading pretrained model load fail.
cuda change in `models/stylegan2/model.py` in line 137 from 

```
self.weight = nn.Parameter(torch.randn(out_dim, in_dim).div_(lr_mul))
```
to 

```
self.weight = nn.Parameter(torch.randn(out_dim, in_dim).div_(lr_mul)).cuda()
```

cause error 

```
Loading ReStyle e4e from checkpoint: ../pretrained/restyle_e4e_ffhq_encode.pt
Traceback (most recent call last):
  File "E:\workspace\python\Latent-To-Latent-main\training\trainer.py", line 159, in <module>
    train(args)
  File "E:\workspace\python\Latent-To-Latent-main\training\trainer.py", line 38, in train
    training_models = Train_Model(configs,device)
  File "E:\workspace\python\Latent-To-Latent-main\training\train_model.py", line 15, in __init__
    self.encoder = e4e(opts)
  File "E:\workspace\python\Latent-To-Latent-main\models\e4e.py", line 25, in __init__
    self.load_weights()
  File "E:\workspace\python\Latent-To-Latent-main\models\e4e.py", line 41, in load_weights
    self.decoder.load_state_dict(self.__get_keys(ckpt, 'decoder'), strict=True)
  File "D:\soft\python39\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Generator:
	Unexpected key(s) in state_dict: "style.1.weight", "style.2.weight", "style.3.weight", "style.4.weight", "style.5.weight", "style.6.weight", "style.7.weight", "style.8.weight", "conv1.conv.modulation.weight", "to_rgb1.conv.modulation.weight", "convs.0.conv.modulation.weight", "convs.1.conv.modulation.weight", "convs.2.conv.modulation.weight", "convs.3.conv.modulation.weight", "convs.4.conv.modulation.weight", "convs.5.conv.modulation.weight", "convs.6.conv.modulation.weight", "convs.7.conv.modulation.weight", "convs.8.conv.modulation.weight", "convs.9.conv.modulation.weight", "convs.10.conv.modulation.weight", "convs.11.conv.modulation.weight", "convs.12.conv.modulation.weight", "convs.13.conv.modulation.weight", "convs.14.conv.modulation.weight", "convs.15.conv.modulation.weight", "to_rgbs.0.conv.modulation.weight", "to_rgbs.1.conv.modulation.weight", "to_rgbs.2.conv.modulation.weight", "to_rgbs.3.conv.modulation.weight", "to_rgbs.4.conv.modulation.weight", "to_rgbs.5.conv.modulation.weight", "to_rgbs.6.conv.modulation.weight", "to_rgbs.7.conv.modulation.weight". 

```

**Comment by shartoo** [comment]
This error occurs because of bad gpu parameters.
